"""
app/services/pdf.py
"""
import os
import uuid
import logging
from typing import Dict, Any

from jinja2 import Template
from weasyprint import HTML

logger = logging.getLogger(__name__)

# Basic HTML template for an itinerary
ITINERARY_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TripMate Itinerary</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 40px; }
        h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        h2 { color: #1e40af; margin-top: 30px; }
        .details { margin-bottom: 30px; background: #f8fafc; padding: 20px; border-radius: 8px; }
        .day { margin-bottom: 20px; border-left: 4px solid #60a5fa; padding-left: 15px; }
        .footer { margin-top: 50px; text-align: center; color: #94a3b8; font-size: 12px; border-top: 1px solid #e2e8f0; padding-top: 20px;}
    </style>
</head>
<body>
    <h1>Trip Itinerary: {{ destination }}</h1>
    
    <div class="details">
        <p><strong>Trip Name:</strong> {{ trip_name }}</p>
        <p><strong>Dates:</strong> {{ dates }}</p>
        <p><strong>Weather Summary:</strong> {{ weather_summary }}</p>
    </div>

    <h2>Day-by-Day Plan</h2>
    {% for day in itinerary %}
    <div class="day">
        <h3>Day {{ loop.index }}: {{ day.title }}</h3>
        <p>{{ day.description }}</p>
    </div>
    {% endfor %}

    <h2>Packing Checklist</h2>
    <ul>
    {% for item in packing_list %}
        <li>{{ item }}</li>
    {% endfor %}
    </ul>
    
    <h2>Recommendations</h2>
    <p>{{ recommendations }}</p>

    <div class="footer">
        Generated by TripMate AI Concierge
    </div>
</body>
</html>
"""

class PDFService:
    @staticmethod
    def generate_itinerary_pdf(data: Dict[str, Any]) -> str:
        """
        Generates a PDF from the given itinerary data and returns the static URL.
        """
        try:
            template = Template(ITINERARY_TEMPLATE)
            
            # Use fallback values if LLM misses something
            html_content = template.render(
                destination=data.get("destination", "Unknown Destination"),
                trip_name=data.get("trip_name", "My Trip"),
                dates=data.get("dates", "TBD"),
                weather_summary=data.get("weather_summary", "N/A"),
                itinerary=data.get("itinerary", [{"title": "Explore", "description": "Enjoy the city!"}]),
                packing_list=data.get("packing_list", ["Passport", "Clothes", "Charger"]),
                recommendations=data.get("recommendations", "Have a great trip!")
            )
            
            filename = f"itinerary_{uuid.uuid4().hex[:8]}.pdf"
            output_dir = os.path.join(os.getcwd(), "static", "pdfs")
            os.makedirs(output_dir, exist_ok=True)
            output_path = os.path.join(output_dir, filename)
            
            HTML(string=html_content).write_pdf(output_path)
            
            # Assuming main.py mounts /static/ to ./static/
            return f"/static/pdfs/{filename}"
            
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise e
