"""add_destination_city_best_time_duration

Revision ID: 9b2f34a441cb
Revises: 6200fef3a913
Create Date: 2026-08-07 02:32:26.559817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2f34a441cb'
down_revision: Union[str, Sequence[str], None] = '6200fef3a913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('destinations', sa.Column('best_time_to_visit', sa.String(length=200), nullable=True))
    op.add_column('destinations', sa.Column('duration_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'duration_days')
    op.drop_column('destinations', 'best_time_to_visit')
    op.drop_column('destinations', 'city')
    # ### end Alembic commands ###
