"""Add Itinerary and DayPlan models

Revision ID: d3edd248919b
Revises: 9b2f34a441cb
Create Date: 2026-08-07 03:04:19.880184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3edd248919b'
down_revision: Union[str, Sequence[str], None] = '9b2f34a441cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('budget_estimate', sa.Text(), nullable=True),
    sa.Column('packing_checklist', sa.Text(), nullable=True),
    sa.Column('restaurant_recommendations', sa.Text(), nullable=True),
    sa.Column('local_attractions', sa.Text(), nullable=True),
    sa.Column('weather_suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_created_at'), 'itineraries', ['created_at'], unique=False)
    op.create_index(op.f('ix_itineraries_is_deleted'), 'itineraries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_itineraries_trip_id'), 'itineraries', ['trip_id'], unique=True)
    op.create_table('day_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('day_no', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('day_no >= 1', name='ck_dayplan_day_no_positive'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dayplan_itinerary_day', 'day_plans', ['itinerary_id', 'day_no'], unique=True)
    op.create_index(op.f('ix_day_plans_created_at'), 'day_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_day_plans_is_deleted'), 'day_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_day_plans_itinerary_id'), 'day_plans', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_plans_itinerary_id'), table_name='day_plans')
    op.drop_index(op.f('ix_day_plans_is_deleted'), table_name='day_plans')
    op.drop_index(op.f('ix_day_plans_created_at'), table_name='day_plans')
    op.drop_index('idx_dayplan_itinerary_day', table_name='day_plans')
    op.drop_table('day_plans')
    op.drop_index(op.f('ix_itineraries_trip_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_is_deleted'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_created_at'), table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###
